AP-22864: Revert "DEVOPS-2351: Use jsoup method to strip namespace ..."
This reverts commit 7771f85fd37f5ab147d05c1450897721d3f444af.

Can't really explain the behavior but parsing the website linked in the ticket causes a regression.
https://www.sec.gov/Archives/edgar/data/320193/000032019323000106/aapl-20230930.htm

java.lang.NullPointerException: Cannot invoke "String.length()" because the return value of "org.knime.core.data.xml.XMLCellContent.getStringValue()" is null
	at org.knime.core.data.xml.XMLCellFactory.create(XMLCellFactory.java:164)
	at org.knime.rest.nodes.webpageretriever.WebpageRetrieverNodeModel.addBodyValuesToCells(WebpageRetrieverNodeModel.java:196)
	at org.knime.rest.nodes.common.RestNodeModel$ResponseHandler.handleFirstResponse(RestNodeModel.java:1179)
	at org.knime.rest.nodes.common.AbstractRequestExecutor.firstResponseToDataCells(AbstractRequestExecutor.java:335)

(AP-22864 - Webpage Retriever fails for some webpages)