AP-20749: Remove no-op `Interceptor` from `NTLMAuthentication`
There were "random" test failures with that particular exception:
junit.framework.AssertionFailedError: Thread default-workqueue-4 has thrown an uncaught ClassCastException: class org.knime.rest.internals.NTLMAuthentication$1 cannot be cast to class org.apache.cxf.phase.PhaseInterceptor (org.knime.rest.internals.NTLMAuthentication$1 is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @12a787f8; org.apache.cxf.phase.PhaseInterceptor is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @7debf26c)
	at org.knime.testing.core.ng.WorkflowUncaughtExceptionsTest.run(WorkflowUncaughtExceptionsTest.java:125)
	at org.knime.testing.core.ng.WorkflowTestSuite.run(WorkflowTestSuite.java:250)

Since there is a test case that tests 401 errors we can remove this 'old' code.

AP-20749 (Apache CXF's HttpClient-SelectorManager threads run indefinitely)